blank_issues_enabled: false
contact_links:
  - name: Ask a question or discuss a topic
    url: https://github.com/Team-B1ND/B1ND-AUTH-TEMPLATE/discussions
    about: Ask questions or discuss with other users in discussions.
  - name: Feature or documentation request
    url: https://github.com/Team-B1ND/B1ND-AUTH-TEMPLATE/discussions/categories/ideas
    about: Open a feature or documentation request in discussions.