name: Notify Discord

on:
  workflow_run:
    workflows: ["Label Issue"]
    types: [completed]
    branches: [main]

permissions:
  actions: read
  issues: read

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Get Issue Information
        id: get-issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_number=$(gh api "/repos/${{ github.repository }}/issues?state=open" --jq '.[0].number')
          issue_title=$(gh api "/repos/${{ github.repository }}/issues/$issue_number" --jq '.title')
          issue_body=$(gh api "/repos/${{ github.repository }}/issues/$issue_number" --jq '.body')
          issue_url="https://github.com/${{ github.repository }}/issues/$issue_number"
          echo "issue_number=$issue_number" >> $GITHUB_ENV
          echo "issue_title=$issue_title" >> $GITHUB_ENV
          echo "issue_body=$issue_body" >> $GITHUB_ENV
          echo "issue_url=$issue_url" >> $GITHUB_ENV

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST "$DISCORD_WEBHOOK" \
          -H "Content-Type: application/json" \
          -d '{
            "username": "GitHub Bot",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "content": "ðŸš¨ **New Issue Created** ðŸš¨",
            "embeds": [{
              "title": "'"${{ env.issue_title }}"'",
              "url": "'"${{ env.issue_url }}"'",
              "description": "'"${{ env.issue_body }}"'",
              "color": 5814783,
              "fields": [
                {
                  "name": "Author",
                  "value": "${{ github.actor }}"
                }
              ]
            }]
          }'
